#!/bin/bash
# you can run the scrapping for the various 'votes' as bash commands
# from the samples folder or any folder with the pdfs
budget -f 124 -l 178 -n agriculture 2011-12.pdf
budget -o -f 124 -l 178 -n agriculture-2 2011-12.pdf

budget -f 214 -l 237 -n works 2011-12.pdf
budget -o -f 214 -l 237 -n works-2 2011-12.pdf

budget -f 311 -l 370 -n education 2011-12.pdf
budget -o -f 311 -l 370 -n education-2 2011-12.pdf

budget -f 377 -l 429 -n health 2011-12.pdf
budget -o -f 377 -l 429 -n health-2 2011-12.pdf

budget -f 494 -l 525 -n water-environment 2011-12.pdf
budget -o -f 494 -l 525 -n water-environment-2 2011-12.pdf

budget -f 530 -l 542 -n social 2011-12.pdf
budget -o -f 530 -l 542 -n social-2 2011-12.pdf
