#!/bin/bash
# you can run the scrapping for the various 'votes' as bash commands
# from the samples folder or any folder with the pdfs
budget -f 138 -l 207 -n agriculture 2014-15.pdf
budget -o -f 138 -l 207 -n agriculture-2 2014-15.pdf

budget -f 214 -l 225 -n works 2014-15.pdf
budget -o -f 214 -l 225 -n works-2 2014-1.pdf

budget -f 363 -l 429 -n education 2014-15.pdf
budget -o -f 363 -l 429 -n education-2 2014-15.pdf

budget -f 437 -l 501 -n health 2014-15.pdf
budget -o -f 437 -l 501 -n health-2 2014-15.pdf

budget -f 579 -l 615 -n water-environment 2014-15.pdf
budget -o -f 579 -l 615 -n water-environment-2 2014-15.pdf

budget -f 621 -l 655 -n social 2014-15.pdf
budget -o -f 621 -l 655 -n social-2 2014-15.pdf
